# Generated by Django 2.1.1 on 2019-07-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('sha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_context', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=30)),
                ('commit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_providers.Commit')),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='repo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_providers.Repo'),
        ),
    ]
