# Generated by Django 2.1.1 on 2019-07-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='repo_id',
            new_name='repo',
        ),
    ]
