# Generated by Django 2.1.1 on 2019-07-21 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('git_providers', '0002_auto_20190721_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
