# Generated by Django 2.1.1 on 2019-07-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_providers', '0003_auto_20190721_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='parent_sha',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
