# Generated by Django 2.1.1 on 2019-07-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_providers', '0004_commit_parent_sha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitParenthood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_sha', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='commitstatus',
            old_name='commit_id',
            new_name='commit',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='parent_sha',
        ),
        migrations.AddField(
            model_name='commitparenthood',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_providers.Commit'),
        ),
    ]
