# Generated by Django 2.1.1 on 2019-07-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_providers', '0005_auto_20190721_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitparenthood',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='git_providers.Commit'),
        ),
    ]
