# Generated by Django 2.1.1 on 2019-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_providers', '0006_auto_20190721_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitstatus',
            name='ext_id',
            field=models.CharField(default='anodedault', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitstatus',
            name='message',
            field=models.TextField(default='nomessage'),
            preserve_default=False,
        ),
    ]
