# Generated by Django 2.1.1 on 2019-07-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_providers', '0007_auto_20190721_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitstatus',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='git_providers.Commit'),
        ),
    ]
